[project]
name = "agent"
version = "0.1.0"
description = "Trading agent with access to tools via MCP"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.3.0",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
    "ta-lib>=0.6.3",
]
